bmlt-enabled/crouton

- contribute.md
- crouton.php
- js/bmlt_tabs.js
- readme.txt
> Add County Dropdown

- js/bmlt_tabs.js
ill do better next time I swear, just give me another shot. my bad.
> js bug from last pull county dd

- crouton.php
- js/bmlt_tabs.js
- readme.txt
ref #5
working example.
https://charlestonna.org/ignoreform/
> adding Area Dropdown 

- crouton.php
- js/bmlt_tabs.js
- js/bmlt_tabs_distance.js
- readme.txt
this adds the show_distance attribute to bmlt_tabs shortcode. seperate js file that will only get loaded if option is set. I removed all the other google js stuff as it wasn't needed or necessary.
ref #3
> add distance option

- crouton.php
just saw your comment but nothing serious in here maybe merge this first?
> formatting from my previous commits and casing

- crouton.php
the sort for the meeting list dropdown was being sorted by the service body id number not by the alphabetical name, also if theres a better way of doing this go for it. this is what i came up with which is TESTED ha and works.
> fix area sort

- crouton.php
- js/bmlt_tabs.js
- partials/_instructions.php
- partials/views/_meetings.php
- readme.txt
> add state dropdown option #48

- crouton.php
oops this should probably be disabled by default.
> state dropdown should not be default

- crouton.php
- partials/_instructions.php
- readme.txt
there was weird stuff in diff, also should of been working off branch
> add abilty to only display used formats, fixed weird diff #73

- .travis.yml
- contribute.md
Travis Build
[https://travis-ci.org/bmlt-enabled/crouton/builds/477967342](https://travis-ci.org/bmlt-enabled/crouton/builds/477967342)
Bucket
[https://archives.bmlt.app/index.html#crouton/](https://archives.bmlt.app/index.html#crouton/)
> Travis build

- .editorconfig
- .gitignore
- .travis.yml
- composer.json
- composer.lock
- crouton.php
- index.php
- partials/views/_byday.php
- partials/views/_cities.php
- partials/views/_weekdays.php
added linting to travis, cleanup for PSR-1
> Code cleanup

- croutonjs/src/js/crouton-core.js
ref #106, this doesn't solve punny code incompatibility but should cover the rest
> Better es5 compat

- croutonjs/src/js/crouton-core.js
- croutonjs/src/templates/header.hbs
ok figured it out
fix for #112
> add class to selects on header template

- .travis.yml
forgot crouton has wordpress and js
> crouton adjustments for travis

- crouton.php
- croutonjs/dist/templates/themes/orange-monster.css
> adding orange monster theme

- .travis.yml
closes https://github.com/bmlt-enabled/crouton/issues/259
> publish croutonjs to npm on tag

- crouton.php
- croutonjs/src/js/crouton-core.js
- readme.txt
fixes https://github.com/bmlt-enabled/crouton/issues/289
> fix same day sorting

- .github/workflows/pull-requests.yml
- .travis.yml
- composer.json
- composer.lock
- croutonjs/src/js/crouton-core.js
use this to avoid whitespace diffs https://github.com/bmlt-enabled/crouton/pull/306/files?diff=unified&w=1
> master formats for diff languages

- readme.txt
just realized that he was never added
> adding jbraswell as a contributor

- crouton.php
- croutonjs/src/js/crouton-core.js
- partials/_instructions.php
- readme.txt
> add support for [service_body_names] shortcode; improve documentation

- Dockerfile
- crouton.php
- croutonjs/src/js/crouton-core.js
- croutonjs/src/js/crouton-localization.js
- croutonjs/src/templates/header.hbs
- croutonjs/src/templates/meetings.hbs
- package-lock.json
- package.json
- partials/_instructions.php
- readme.txt
> venue types filter #327 #330

- .eslintrc
- croutonjs/src/js/crouton-core.js
- croutonjs/src/js/fetch-jsonp.js
- croutonjs/src/js/promises-polyfill.js
- croutonjs/src/templates/meetings.hbs
- gulpfile.js
- package-lock.json
- package.json
Two things already discussed with @jbraswell:
We cannot eliminate the GetFormats call for two reasons:
1) It's how crouton targets `VM`, `TC`, and `HY`, to get the master format ID to get the language description.
2) It's how crouton determines if the meeting is `TC`, which is not available other than getting the master format ID and then seeing if the meeting contains that format code.
> venue type field changes

- Dockerfile
- crouton.php
- croutonjs/src/js/crouton-core.js
- readme.txt
closes https://github.com/bmlt-enabled/crouton/issues/371
> fix for extra meetings

- crouton.php
- croutonjs/src/templates/meetings.hbs
- readme.txt
potential fix for https://github.com/bmlt-enabled/crouton/issues/385
> dont show end time if open ended duration

- crouton.php
> Update user agent

- .github/ISSUE_TEMPLATE/language_support.md
- .github/workflows/latest.yml
- .github/workflows/pull-requests.yml
- contribute.md
- croutonjs/README.md
- partials/_instructions.php
fyi, the doc links and everything will still work as a ref is kept from master to main
> rename to main

- crouton.php
- readme.txt
sorry, forgot to bump the version
> version bump

- crouton.php
- croutonjs/src/js/crouton-default-templates.js
- readme.txt
Fixes for bugs reported yesterday
> Fixes part 2

- crouton.php
- readme.txt
> Shortcode attributes should have precedence

- crouton.php
- croutonjs/meetingMap/js/meeting_map.js
- croutonjs/meetingMap/js/osmDelegate.js
The last commit generates a NPE in the console when the modal dialog is generated
> fix null pointer exception

- crouton.php
- croutonjs/meetingMap/js/meeting_map.js
- croutonjs/meetingMap/meeting_map.php
- js/bmlt_tabs_admin.js
- readme.txt
Add an option to place generated JS in footer
> Insert js into footer

- crouton.php
- croutonjs/meetingMap/js/meeting_map.js
- croutonjs/src/js/crouton-core.js
- readme.txt
> Fix-for-#497

- crouton.php
- readme.txt
> Fix for #371
